server:
  port: 9030
  servlet.context-path: /intelligence
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lovable-intelligence-db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  ai:
    model.chat: openai
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openrouter/auto
          temperature: 0.2
      embedding:
        options:
          model: qwen/qwen3-embedding-8b
